# Generated by Django 5.2.5 on 2025-11-12 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_mall_restaurant_remove_review_place_delete_place_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Mall', 'Mall')], max_length=50)),
                ('date', models.DateField()),
                ('status', models.CharField(default='Pending', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Hotel', 'Hotel'), ('Restaurant', 'Restaurant'), ('Mall', 'Mall')], max_length=50)),
                ('comment', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
    ]
