# Generated by Django 5.2.5 on 2025-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_hotel_image_alter_mall_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(upload_to='imagesData/'),
        ),
        migrations.AlterField(
            model_name='mall',
            name='image',
            field=models.ImageField(upload_to='imagesData/'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(upload_to='imagesData/'),
        ),
    ]
